name: 🛠 Feature Request
description: Create a feature request for the application
title: 'Feature: '
labels: ['✨ enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this form as completely as possible.
  - type: input
    id: location 
    attributes:
      label: Describe the where the feature lives
      description: Please describe the feature as clear and concise as possible. Remember to stay in the context of a user using the application.
    validations:
      required: true
  - type: textarea
    id: user-story 
    attributes:
      label: Describe the User Story
      description: Please describe the feature as clear and concise as possible. Remember to stay in the context of a user using the application.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like to see
      description: Please describe the solution you would like to see. Adding example usage is a good way to provide context.
    validations:
      required: true